name: taartu_mobile
description: "Taartu Booking Marketplace - Cross-platform mobile app for salon bookings"
publish_to: 'none'

version: 1.0.0+100

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  
  # HTTP Client
  dio: ^5.4.3
  dio_cookie_manager: ^3.1.1
  http: ^1.2.0
  
  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^16.0.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Notifications
  flutter_local_notifications: ^19.3.1
  firebase_messaging: ^15.2.10
  
  # Analytics
  mixpanel_flutter: ^2.4.4
  
  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9
  
  # Image & Camera
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Payment Integration
  webview_flutter: ^4.7.0
  
  # Utils
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.2
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.3
  cookie_jar: ^4.0.8
  
  # Legal & Documentation
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true 